theme: jekyll-theme-minimal
title: 'Proteomics Analysis in Limma'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Setup
  - title: Setup and file downloads
    url: preliminaries/download
    
  - heading: Analysis in Limma
  - title: Analysis in Limma
    url: limma_proteomics_analysis_tutorial_2024
