theme: jekyll-theme-minimal
title: 'RNA Seq Differential Expression and Enrichment Analysis'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Preliminaries
  - title: Before the course
    url: preliminaries/before
  - title: File downloads
    url: preliminaries/download
    
  - heading: Data Analysis
  - title: Differential Expression
    url: data_analysis/DE_Analysis_with_quizzes_fixed
  - title: Enrichment Analysis
    url: data_analysis/enrichment_with_quizzes_fixed
  - title: R Code for Quizzes
    url: data_analysis/R_code_for_quizzes
  
  - heading: Upcoming
  - title: Upcoming Bioinformatics Core Courses
    url: base/courses
